name: Build and Deploy API Gateway

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package*.json'
      - 'Dockerfile'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Docker image
        run: |
          docker build -t myregistry.com/api-gateway:latest .
          docker push myregistry.com/api-gateway:latest

      - name: Update deployment to use registry
        run: |
          kubectl patch deployment api-gateway -p '{"spec":{"template":{"spec":{"containers":[{"name":"api-gateway","image":"myregistry.com/api-gateway:latest","imagePullPolicy":"Always"}]}}}}'
          kubectl rollout status deployment/api-gateway