name: Build and Deploy API Gateway

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package*.json'
      - 'Dockerfile'
      - 'k8s/**'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t api-gateway:latest .

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/api-gateway api-gateway=api-gateway:latest
          kubectl rollout status deployment/api-gateway