name: Build and Deploy API Gateway

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package*.json'
      - 'Dockerfile'
      - 'k8s/**'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t api-gateway:latest .

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml
          
          # 배포 확인 및 롤아웃 상태 체크
          kubectl rollout status deployment/api-gateway